# -*- coding: utf-8 -*-
"""Scraping googleplay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Amaliya-code/UTS-GooglePlayScraper/blob/main/%20Scraping%20googleplay.ipynb
"""

!pip install google-play-scraper

from google_play_scraper import reviews, Sort
import csv

from google_play_scraper import reviews, Sort
import csv

result, _ = reviews(
    'com.dafturn.mypertamina',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=200,
    filter_score_with=None
)

filename = 'ulasan_mypertamina.csv'

with open(filename, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(
        f,
        fieldnames=['userName', 'score', 'at', 'content']
    )

    writer.writeheader()

    for review in result:
        writer.writerow({
            'userName': review['userName'],
            'score': review['score'],
            'at': review['at'],
            'content': review['content']
        })

print(f"Berhasil menyimpan {len(result)} ulasan ke '{filename}'")

!pip install transformers torch pandas

import pandas as pd
from transformers import pipeline

# Membaca file CSV hasil scraping
df = pd.read_csv('ulasan_mypertamina.csv')

# Menampilkan 5 data pertama
df.head()

classifier = pipeline(
    "sentiment-analysis",
    model="w11wo/indonesian-roberta-base-sentiment-classifier"
)

df['sentiment'] = df['content'].astype(str).apply(
    lambda x: classifier(x[:512])[0]['label']
)

df.head()

df.to_csv('hasil_sentiment_mypertamina.csv', index=False)

df['sentiment'].value_counts()

import matplotlib.pyplot as plt

df['sentiment'].value_counts().plot(kind='bar')

plt.title('Analisis Sentimen MyPertamina')
plt.xlabel('Sentiment')
plt.ylabel('Jumlah')

plt.show()

df.to_csv('hasil_sentiment_mypertamina.csv', index=False)

